### ISSUE TITLE
Incorrect Code Point at 0x60

### ISSUE THREAD

**Issue by gitjeff2** [dj51d/cbmcodecs#1]
It looks like when Linus Walleij created his [PETSCII to Unicode table](https://dflund.se/~triad/krad/recode/petscii_c64en_lc.txt) he made an off-by-one error and that mistake made it into your codec tables. 

He defines 0x60 as follows:

```
0x60    0x2501  #BOX DRAWINGS LIGHT HORIZONTAL
```

However, "box drawings light horizontal" is 0x2500. (The code point 0x2501 is "box drawings heavy horizontal.") See the Wikipedia article on [Box Drawing Characters](https://en.wikipedia.org/wiki/Box-drawing_character) for details.

Other projects also use 0x2500 for this code point.

**Comment by irmen** [comment]
@gitjeff2 this is now fixed in my fork of this library

**Comment by irmen** [comment]
@dj51d merging my PR has resolved this issue now (and issue #3  as well)
